apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: cnn-pipeline
    name: cnn-pipeline
  name: cnn-pipeline
spec:
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    secrets: null
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |+
        #!groovy
        node() {
          stage ('build and deploy') {
            openshiftBuild(namespace: 'mnist',
                           buildConfig: 'tf-cnn',
                           showBuildLogs: 'true',
                           waitTime: '300000')
          }
          stage ('scale deployment') {
            openshiftScale(namespace: 'mnist',
                           deploymentConfig: 'tf-cnn',
                           waitTime: '300000',
                           replicaCount: '1')
          }
          stage ('verify deployment') {
            openshiftVerifyDeployment(namespace: 'mnist',
                           depCfg: 'tf-cnn',
                           replicaCount:'1',
                           verifyReplicaCnt: 'true',
                           waitTime: '300000')
          }
        }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
status:
  lastVersion: 0
